services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/luaDev
      - /luaDev/node_modules
    depends_on:
      - db
    env_file:
      - dotenv_files/.env
    networks:
      - lua-network

  db:
    image: postgres:16
    container_name: postgresql_db
    restart: always
    env_file:
      - dotenv_files/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - lua-network

networks:
  lua-network:
    driver: bridge

volumes:
  pgdata:
